workflows:
  expo54_debug_build:
    name: Expo 54 Debug Build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      vars:
        NODE_OPTIONS: "--max-old-space-size=4096"
        EXPO_NO_TELEMETRY: "1"
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli
          npm ci || npm install
      - name: Ensure index.sh executable
        script: chmod +x index.sh
      - name: Build debug (native)
        script: |
          echo "🔧 Running native build via index.sh..."
          ./index.sh --native-android -p debug || {
            echo "⚠️ Fallback ke manual Gradle build"
            cd android && ./gradlew assembleDebug --stacktrace
          }
      - name: Collect artifact (multi-path Expo 54 fix)
        script: |
          mkdir -p builds/android
          APK=$(find builds/android -name "*.apk" -o -path "android/app/build/outputs/apk/debug/*.apk" | head -n 1)
          test -n "$APK" || { echo "❌ No debug APK produced"; exit 1; }
          cp "$APK" builds/android/app-debug.apk
          echo "✅ Wrote builds/android/app-debug.apk"
    artifacts:
      - builds/android/*.apk
    publishing:
      email:
        recipients:
          - "youremail@example.com"
