workflows:
  expo_apk_gradle87:
    name: "Expo APK (Gradle 8.7 + AGP 8.6.1 + Kotlin 2.0.21)"
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      java: 17
      node: 20
    scripts:
      - name: Ensure deps
        script: |
          set -euxo pipefail
          npm ci || npm install

      - name: Verify wrapper & versions (must be Gradle 8.7)
        script: |
          set -euxo pipefail
          grep distributionUrl android/gradle/wrapper/gradle-wrapper.properties
          cd android
          chmod +x gradlew || true
          ./gradlew --version
          java -version
          cd ..

      - name: Build debug APK (assembleDebug)
        script: |
          set -euxo pipefail
          cd android
          ./gradlew clean assembleDebug --no-daemon --console=plain --stacktrace --info -Pkotlin.compiler.execution.strategy=in-process
          cd ..
      - name: Collect artifact
        script: |
          set -euxo pipefail
          mkdir -p builds/android
          APK=$(find android/app/build -type f -name "*debug*.apk" | head -n 1 || true)
          test -n "$APK" || { echo "No debug APK produced"; exit 1; }
          cp "$APK" builds/android/app-debug.apk
    artifacts:
      - builds/android/app-debug.apk
