workflows:
  expo_debug_apk:
    name: Expo Debug APK (force assemble)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      node: 20
      npm: 9
      java: 17
      vars:
        EXPO_NO_INTERACTIVE: "true"
        NODE_ENV: "development"
    scripts:
      - name: Install dependencies
        script: |
          npm ci || npm install
          npm install -g expo-cli
      - name: Ensure icons
        script: |
          mkdir -p assets
          [ -f assets/icon.png ] || curl -sL -o assets/icon.png https://cdn.jsdelivr.net/gh/expo/expo@main/templates/expo-template-bare-minimum/assets/icon.png
          [ -f assets/adaptive-icon.png ] || curl -sL -o assets/adaptive-icon.png https://cdn.jsdelivr.net/gh/expo/expo@main/templates/expo-template-bare-minimum/assets/adaptive-icon.png
      - name: Prebuild android
        script: |
          rm -rf android
          npx expo prebuild --platform android --clean --non-interactive || true
          ls android || echo "⚠️ Android folder mungkin kosong, teruskan paksa build"
      - name: Force Gradle wrapper
        script: |
          cd android
          [ -f gradlew ] || ./gradlew help || (gradle wrapper || true)
          chmod +x gradlew || true
          cd ..
      - name: Build APK (fallback ke assembleRelease jika debug tiada)
        script: |
          cd android
          ./gradlew tasks | grep assembleDebug || ./gradlew tasks
          ./gradlew assembleDebug --stacktrace || ./gradlew assembleRelease --stacktrace || true
          cd ..
      - name: List output dir
        script: |
          echo "📁 Output build:"
          find android/app/build/outputs -type f -print || echo "❌ Tiada fail dijumpai"
      - name: Collect artifact (auto-detect)
        script: |
          APK_PATH=$(find android/app/build/outputs -type f -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "❌ Tiada APK dijumpai — semak prebuild atau Gradle logs"
            exit 1
          fi
          mkdir -p build
          cp "$APK_PATH" build/forensik-debug.apk
          echo "✅ Disalin ke build/forensik-debug.apk"
    artifacts:
      - build/forensik-debug.apk
