name: Build APK (Forensik Belerang Merah)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Install deps
        run: |
          npm ci || npm install

      # Optional: gunakan token Expo kalau ada (set di GitHub Secrets)
      - name: Expo login (optional)
        if: ${{ secrets.EXPO_TOKEN != '' }}
        run: npx expo login --token ${{ secrets.EXPO_TOKEN }}

      # Jika index.sh wujud, gunakan skrip custom projek; kalau tak, terus guna EAS build
      - name: Build APK
        run: |
          chmod +x ./index.sh || true
          if [ -x "./index.sh" ]; then
            echo "index.sh dikesan → guna aliran custom projek"
            ./index.sh --apk --profile=preview --local
          else
            echo "index.sh tiada → fallback ke EAS build direct"
            eas build --platform android --profile preview --local --non-interactive --output=./app-preview.apk
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-preview-apk
          path: |
            **/*.apk
            builds/**/*.apk
            app-*.apk
          if-no-files-found: error
